services:
  airflow-worker:
    image: apache/airflow:2.9.3
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@52.78.27.154:5432/airflow
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@52.78.27.154:5432/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://52.78.27.154:6379/0
      AIRFLOW__CORE__FERNET_KEY: ''  
      AIRFLOW__WEBSERVER__BASE_URL: http://52.78.27.154.232:8080
      AIRFLOW__WEBSERVER__WEB_SERVER_HOST: 52.78.27.154
      AIRFLOW__WEBSERVER__WEB_SERVER_PORT: 8080
      AIRFLOW__LOGGING__BASE_LOG_FOLDER: /opt/airflow/logs
      AIRFLOW__LOGGING__REMOTE_LOGGING: 'True'
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./tmp:/tmp
    command: celery worker
