services:
  airflow-worker:
    image: apache/airflow:2.9.3
    environment:
      AIRFLOW_HOME: /opt/airflow
    command:
      - -c
      - |
        chown -R "${AIRFLOW_UID}:0" /sources/{logs,dags,plugins}
        airflow db upgrade
        airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@airflow.com
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./tmp:/tmp
      - ./airflow.cfg:/opt/airflow/airflow.cfg 
    command: celery worker
