version: '3'
services:
    airflow-worker:
          image: apache/airflow:2.9.3
          environment:
            AIRFLOW__CORE__EXECUTOR: CeleryExecutor
            AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@15.165.237.250:5432/airflow
            AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@15.165.237.250:5432/airflow
            AIRFLOW__CELERY__BROKER_URL: redis://15.165.237.250:6379/0
            AIRFLOW__CORE__FERNET_KEY: ''  
            AIRFLOW__WEBSERVER__BASE_URL: http://15.165.237.250:8080
            AIRFLOW__WEBSERVER__WEB_SERVER_HOST: 0.0.0.0
            AIRFLOW__WEBSERVER__WEB_SERVER_PORT: 8080
          volumes:
            - ./airflow.cfg:/opt/airflow/airflow.cfg
            - ./dags:/opt/airflow/dags                                                                            
          command: celery worker
