services:
  airflow-worker:
    image: apache/airflow:2.9.3
    environment:
      AIRFLOW_HOME: /opt/airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./tmp:/tmp
      - ./airflow.cfg:/opt/airflow/airflow.cfg 
    command: celery worker
