version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app/src
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: 'fortest.settings'
      DATABASE_NAME: 'team_hori_db'
      DATABASE_USER: 'postgres'
      DATABASE_PASSWORD: 'ZbEwxdE3tENdaspoUUs3'
      DATABASE_HOST: 'team-hori-2.ch4xfyi6stod.ap-northeast-2.rds.amazonaws.com'
      DATABASE_PORT: '5432'
      DATABASE_OPTIONS: '-c timezone=UTC'
    restart: always

networks:
  default:
    driver: bridge
