name: Pull Changes from dags Directory

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'airflow/dags/**'

jobs:
  pull-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set user-specific path
        id: get_user_path
        run: echo "::set-output name=path::/c/Users/${{ github.actor }}/TourSherpa/airflow/dags"

      - name: Pull changes from dags directory
        run: |
          cd ${{ steps.get_user_path.outputs.path }}
          git pull origin main
          git pull origin develop
