name: Update Airflow DAGs

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'dags/**'

jobs:
  update-dags:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Determine user-specific path
        id: get_user_path
        run: echo "::set-output name=path::/c/Users/${{ github.actor }}/TourSherpa/dags"

      - name: Update Docker Airflow DAGs
        run: |
          DOCKER_CONTAINER_NAME="your_airflow_container_name"
          BRANCH=$(if [ "${{ github.ref }}" == "refs/heads/main" ]; then echo "main"; else echo "develop"; fi)
          DAGS_PATH="${{ steps.get_user_path.outputs.path }}"

          docker exec $DOCKER_CONTAINER_NAME bash -c "cd ${DAGS_PATH} && git fetch origin && git checkout $BRANCH && git pull"
        env:
          DOCKER_CONTAINER_NAME: your_airflow_container_name
