# Generated by Django 4.2.14 on 2024-07-31 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('category', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TravelEvent',
            fields=[
                ('EventID', models.CharField(default='none', max_length=255, primary_key=True, serialize=False)),
                ('Title', models.CharField(blank=True, default='none', max_length=1000, null=True)),
                ('Description', models.CharField(blank=True, default='none', max_length=5000)),
                ('Category', models.CharField(blank=True, default='none', max_length=255, null=True)),
                ('Rank', models.IntegerField(blank=True, default=0, null=True)),
                ('PhqAttendance', models.IntegerField(blank=True, default=0, null=True)),
                ('TimeStart', models.CharField(blank=True, default='none', max_length=50)),
                ('TimeEnd', models.CharField(blank=True, default='none', max_length=50)),
                ('LocationID', models.CharField(blank=True, default='none', max_length=50)),
                ('Address', models.TextField(blank=True, default='none', null=True)),
                ('Region', models.CharField(blank=True, default='none', max_length=255, null=True)),
                ('Country', models.CharField(blank=True, default='none', max_length=50, null=True)),
                ('PredictedEventSpend', models.FloatField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'travel_events',
            },
        ),
    ]
