# Generated by Django 4.2.14 on 2024-08-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('airline_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('airline_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'airline',
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('airport_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('airport_name', models.CharField(max_length=100)),
                ('airport_location', models.CharField(max_length=200)),
                ('country_code', models.CharField(max_length=50)),
                ('country_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'airport',
            },
        ),
        migrations.CreateModel(
            name='EventsForHotel',
            fields=[
                ('Google_Place_Id', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('HOTELNAME', models.CharField(blank=True, max_length=512, null=True)),
                ('EventID', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'events_for_hotel',
            },
        ),
        migrations.CreateModel(
            name='FlightFrom',
            fields=[
                ('airline_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('departure', models.CharField(max_length=50)),
                ('departure_at', models.DateTimeField()),
                ('arrival', models.CharField(max_length=50)),
                ('arrival_at', models.DateTimeField()),
                ('duration', models.CharField(max_length=50)),
                ('seats', models.IntegerField()),
                ('price', models.FloatField()),
            ],
            options={
                'db_table': 'flight_from',
            },
        ),
        migrations.CreateModel(
            name='FlightTo',
            fields=[
                ('airline_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('departure', models.CharField(max_length=50)),
                ('departure_at', models.DateTimeField()),
                ('arrival', models.CharField(max_length=50)),
                ('arrival_at', models.DateTimeField()),
                ('duration', models.CharField(max_length=50)),
                ('seats', models.IntegerField()),
                ('price', models.FloatField()),
            ],
            options={
                'db_table': 'flight_to',
            },
        ),
        migrations.CreateModel(
            name='HotelList',
            fields=[
                ('event_id', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('google_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('google_address', models.CharField(blank=True, max_length=1000, null=True)),
                ('google_rating', models.FloatField(blank=True, null=True)),
                ('google_user_ratings_total', models.IntegerField(blank=True, null=True)),
                ('google_place_id', models.CharField(blank=True, max_length=512, null=True)),
                ('agoda_hotel_id', models.CharField(blank=True, max_length=512, null=True)),
                ('agoda_chain_id', models.CharField(blank=True, max_length=512, null=True)),
                ('agoda_chain_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('agoda_hotel_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('agoda_city', models.CharField(blank=True, max_length=512, null=True)),
                ('agoda_star_rating', models.FloatField(blank=True, null=True)),
                ('agoda_longitude', models.FloatField(blank=True, null=True)),
                ('agoda_latitude', models.FloatField(blank=True, null=True)),
                ('agoda_checkin', models.CharField(blank=True, max_length=100, null=True)),
                ('agoda_checkout', models.CharField(blank=True, max_length=100, null=True)),
                ('google_number_of_reviews', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hotel_list',
            },
        ),
        migrations.CreateModel(
            name='HotelsForEvent',
            fields=[
                ('EventID', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('Title', models.CharField(blank=True, max_length=1000, null=True)),
                ('Agoda_Hotels', models.TextField(blank=True, null=True)),
                ('Google_Place_Hotels', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hotels_for_event',
            },
        ),
        migrations.CreateModel(
            name='NearestAirport',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('airport_code', models.CharField(max_length=100)),
                ('airport_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'nearest_airports',
            },
        ),
        migrations.CreateModel(
            name='TravelEvent',
            fields=[
                ('EventID', models.CharField(default='none', max_length=255, primary_key=True, serialize=False)),
                ('Title', models.CharField(blank=True, default='none', max_length=1000, null=True)),
                ('Description', models.CharField(blank=True, default='none', max_length=5000)),
                ('Category', models.CharField(blank=True, default='none', max_length=255, null=True)),
                ('Rank', models.IntegerField(blank=True, default=0, null=True)),
                ('PhqAttendance', models.IntegerField(blank=True, default=0, null=True)),
                ('TimeStart', models.CharField(blank=True, default='none', max_length=50)),
                ('TimeEnd', models.CharField(blank=True, default='none', max_length=50)),
                ('LocationID', models.CharField(blank=True, default='none', max_length=50)),
                ('Address', models.TextField(blank=True, default='none', null=True)),
                ('Region', models.CharField(blank=True, default='none', max_length=255, null=True)),
                ('Country', models.CharField(blank=True, default='none', max_length=50, null=True)),
                ('PredictedEventSpend', models.FloatField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'travel_events',
            },
        ),
    ]
