# Generated by Django 4.2.14 on 2024-08-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsForHotel',
            fields=[
                ('Google_Place_Id', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('HOTELNAME', models.CharField(blank=True, max_length=512, null=True)),
                ('EventID', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hotel.events_for_hotel',
            },
        ),
        migrations.CreateModel(
            name='HotelsForEvent',
            fields=[
                ('EventID', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('Title', models.CharField(blank=True, max_length=1000, null=True)),
                ('Agoda_Hotels', models.TextField(blank=True, null=True)),
                ('Google_Place_Hotels', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hotel.hotels_for_event',
            },
        ),
    ]
