# Generated by Django 4.2.14 on 2024-08-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_eventsforhotel_hotelsforevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('airline_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('airline_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'airline',
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('airport_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('airport_name', models.CharField(max_length=100)),
                ('airport_location', models.CharField(max_length=200)),
                ('country_code', models.CharField(max_length=50)),
                ('country_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'airport',
            },
        ),
        migrations.CreateModel(
            name='FlightFrom',
            fields=[
                ('airline_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('departure', models.CharField(max_length=50)),
                ('departure_at', models.CharField(max_length=50)),
                ('arrival', models.CharField(max_length=50)),
                ('arrival_at', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('seats', models.IntegerField()),
                ('price', models.FloatField()),
            ],
            options={
                'db_table': 'flight_from',
            },
        ),
        migrations.CreateModel(
            name='FlightTo',
            fields=[
                ('airline_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('departure', models.CharField(max_length=50)),
                ('departure_at', models.CharField(max_length=50)),
                ('arrival', models.CharField(max_length=50)),
                ('arrival_at', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('seats', models.IntegerField()),
                ('price', models.FloatField()),
            ],
            options={
                'db_table': 'flight_to',
            },
        ),
        migrations.CreateModel(
            name='HotelList',
            fields=[
                ('event_id', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('google_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('google_address', models.CharField(blank=True, max_length=1000, null=True)),
                ('google_rating', models.FloatField(blank=True, null=True)),
                ('google_user_ratings_total', models.IntegerField(blank=True, null=True)),
                ('google_place_id', models.CharField(blank=True, max_length=512, null=True)),
                ('agoda_hotel_id', models.CharField(blank=True, max_length=512, null=True)),
                ('agoda_chain_id', models.CharField(blank=True, max_length=512, null=True)),
                ('agoda_chain_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('agoda_hotel_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('agoda_city', models.CharField(blank=True, max_length=512, null=True)),
                ('agoda_star_rating', models.FloatField(blank=True, null=True)),
                ('agoda_longitude', models.FloatField(blank=True, null=True)),
                ('agoda_latitude', models.FloatField(blank=True, null=True)),
                ('agoda_checkin', models.CharField(blank=True, max_length=100, null=True)),
                ('agoda_checkout', models.CharField(blank=True, max_length=100, null=True)),
                ('google_number_of_reviews', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hotel_list',
            },
        ),
        migrations.AlterModelTable(
            name='eventsforhotel',
            table='events_for_hotel',
        ),
        migrations.AlterModelTable(
            name='hotelsforevent',
            table='hotels_for_event',
        ),
    ]
